# Generated by Django 6.0.4 on 2026-04-22 18:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='ID do cliente')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('possui_fiado', models.BooleanField(default=False, verbose_name='Possui fiado')),
                ('saldo_fiado', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Saldo fiado')),
                ('data_cadastro', models.DateField(verbose_name='Data de cadastro')),
                ('qtd_comprada', models.PositiveIntegerField(default=0, verbose_name='Quantidade comprada')),
                ('total_valor', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total em compras')),
                ('bairro', models.CharField(blank=True, max_length=100, verbose_name='Bairro')),
                ('ultima_compra', models.DateField(blank=True, null=True, verbose_name='Ultima compra')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id_fornecedor', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='ID do fornecedor')),
                ('razao_social', models.CharField(max_length=150, verbose_name='Razao social')),
                ('cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ')),
                ('inscricao_est', models.CharField(blank=True, max_length=20, verbose_name='Inscricao estadual')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('numero', models.CharField(blank=True, max_length=20, verbose_name='Numero')),
                ('comp', models.CharField(blank=True, max_length=100, verbose_name='Complemento')),
                ('bairro', models.CharField(blank=True, max_length=100, verbose_name='Bairro')),
                ('representante', models.CharField(blank=True, max_length=100, verbose_name='Representante')),
                ('rua', models.CharField(max_length=150, verbose_name='Rua')),
                ('cep', models.CharField(max_length=9, verbose_name='CEP')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('uf', models.CharField(max_length=2, verbose_name='UF')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'ordering': ['razao_social'],
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id_funcionario', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='ID do funcionario')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo')),
                ('data_admissao', models.DateField(verbose_name='Data de admissao')),
                ('turno', models.CharField(max_length=30, verbose_name='Turno')),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Salario')),
                ('horas_semanais', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Horas semanais')),
            ],
            options={
                'verbose_name': 'Funcionario',
                'verbose_name_plural': 'Funcionarios',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id_produto', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='ID do produto')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('categoria', models.CharField(blank=True, max_length=100, verbose_name='Categoria')),
                ('unidade', models.CharField(blank=True, max_length=20, verbose_name='Unidade')),
                ('ncm', models.CharField(blank=True, max_length=20, verbose_name='NCM')),
                ('cst', models.CharField(blank=True, max_length=10, verbose_name='CST')),
                ('codigo_barras', models.CharField(blank=True, max_length=50, verbose_name='Codigo de barras')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Preco')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='CompraFornecedor',
            fields=[
                ('id_compra', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='ID da compra')),
                ('data_compra', models.DateField(verbose_name='Data da compra')),
                ('cfop', models.CharField(blank=True, max_length=10, verbose_name='CFOP')),
                ('status', models.CharField(blank=True, max_length=30, verbose_name='Status')),
                ('data_entrega', models.DateField(blank=True, null=True, verbose_name='Data de entrega')),
                ('nota_fiscal', models.CharField(blank=True, max_length=50, verbose_name='Nota fiscal')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor total')),
                ('fornecedor', models.ForeignKey(db_column='id_fornecedor', on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='mercadinho.fornecedor', verbose_name='Fornecedor')),
                ('funcionario', models.ForeignKey(db_column='id_funcionario', on_delete=django.db.models.deletion.PROTECT, related_name='compras_registradas', to='mercadinho.funcionario', verbose_name='Funcionario responsavel')),
            ],
            options={
                'verbose_name': 'Compra de fornecedor',
                'verbose_name_plural': 'Compras de fornecedor',
                'ordering': ['-data_compra'],
            },
        ),
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id_despesa', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='ID da despesa')),
                ('data', models.DateField(verbose_name='Data')),
                ('categoria', models.CharField(max_length=100, verbose_name='Categoria')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor')),
                ('compra', models.ForeignKey(db_column='id_compra', on_delete=django.db.models.deletion.PROTECT, related_name='despesas', to='mercadinho.comprafornecedor', verbose_name='Compra vinculada')),
                ('funcionario', models.ForeignKey(db_column='id_funcionario', on_delete=django.db.models.deletion.PROTECT, related_name='despesas', to='mercadinho.funcionario', verbose_name='Funcionario')),
            ],
            options={
                'verbose_name': 'Despesa',
                'verbose_name_plural': 'Despesas',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='ItemVenda',
            fields=[
                ('id_item_venda', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade_vendida', models.PositiveIntegerField(verbose_name='Quantidade vendida')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Preco unitario')),
                ('desconto_aplicado', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Desconto aplicado')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Subtotal')),
                ('produto', models.ForeignKey(db_column='id_produto', on_delete=django.db.models.deletion.PROTECT, related_name='itens_venda', to='mercadinho.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Item da venda',
                'verbose_name_plural': 'Itens da venda',
                'ordering': ['venda_id', 'produto_id'],
            },
        ),
        migrations.CreateModel(
            name='ItemCompra',
            fields=[
                ('id_item_compra', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor unitario')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Subtotal')),
                ('compra', models.ForeignKey(db_column='id_compra', on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='mercadinho.comprafornecedor', verbose_name='Compra')),
                ('produto', models.ForeignKey(db_column='id_produto', on_delete=django.db.models.deletion.PROTECT, related_name='itens_compra', to='mercadinho.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Item da compra',
                'verbose_name_plural': 'Itens da compra',
                'ordering': ['compra_id', 'produto_id'],
            },
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id_estoque', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='ID do estoque')),
                ('quantidade_atual', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantidade atual')),
                ('quantidade_minima', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Estoque mínimo')),
                ('quantidade_maxima', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Estoque máximo')),
                ('dt_ultima_entrada', models.DateField(blank=True, null=True, verbose_name='Data da última entrada')),
                ('dt_ultima_saida', models.DateField(blank=True, null=True, verbose_name='Data da última saída')),
                ('produto', models.OneToOneField(db_column='id_produto', on_delete=django.db.models.deletion.PROTECT, related_name='estoque', to='mercadinho.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Estoque',
                'verbose_name_plural': 'Estoques',
                'ordering': ['id_estoque'],
            },
        ),
        migrations.AddField(
            model_name='comprafornecedor',
            name='produtos',
            field=models.ManyToManyField(related_name='compras_fornecedor', through='mercadinho.ItemCompra', to='mercadinho.produto', verbose_name='Produtos'),
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id_venda', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='ID da venda')),
                ('data_venda', models.DateField(verbose_name='Data da venda')),
                ('hora', models.TimeField(verbose_name='Hora da venda')),
                ('forma_pagamento', models.CharField(choices=[('dinheiro', 'Dinheiro'), ('pix', 'PIX'), ('cartao_debito', 'Cartão Débito'), ('cartao_credito', 'Cartão Crédito'), ('fiado', 'Fiado')], max_length=20, verbose_name='Forma de pagamento')),
                ('cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.PROTECT, related_name='vendas', to='mercadinho.cliente', verbose_name='Cliente')),
                ('funcionario', models.ForeignKey(db_column='id_funcionario', on_delete=django.db.models.deletion.PROTECT, related_name='vendas', to='mercadinho.funcionario', verbose_name='Funcionario')),
                ('produtos', models.ManyToManyField(related_name='vendas', through='mercadinho.ItemVenda', to='mercadinho.produto', verbose_name='Produtos')),
            ],
            options={
                'verbose_name': 'Venda',
                'verbose_name_plural': 'Vendas',
                'ordering': ['-data_venda', '-hora'],
            },
        ),
        migrations.AddField(
            model_name='itemvenda',
            name='venda',
            field=models.ForeignKey(db_column='id_venda', on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='mercadinho.venda', verbose_name='Venda'),
        ),
        migrations.AddConstraint(
            model_name='itemcompra',
            constraint=models.UniqueConstraint(fields=('compra', 'produto'), name='unique_produto_por_compra'),
        ),
        migrations.AddConstraint(
            model_name='itemvenda',
            constraint=models.UniqueConstraint(fields=('venda', 'produto'), name='unique_produto_por_venda'),
        ),
    ]
