# Generated by Django 6.0.4 on 2026-04-24 03:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercadinho', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='qtd_comprada',
        ),
        migrations.RemoveField(
            model_name='comprafornecedor',
            name='cfop',
        ),
        migrations.RemoveField(
            model_name='estoque',
            name='dt_ultima_entrada',
        ),
        migrations.RemoveField(
            model_name='estoque',
            name='quantidade_maxima',
        ),
        migrations.RemoveField(
            model_name='fornecedor',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='fornecedor',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='fornecedor',
            name='comp',
        ),
        migrations.RemoveField(
            model_name='fornecedor',
            name='inscricao_est',
        ),
        migrations.RemoveField(
            model_name='fornecedor',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='fornecedor',
            name='representante',
        ),
        migrations.RemoveField(
            model_name='fornecedor',
            name='rua',
        ),
        migrations.RemoveField(
            model_name='itemcompra',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='cst',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='ncm',
        ),
        migrations.AddField(
            model_name='comprafornecedor',
            name='entregue',
            field=models.BooleanField(default=False, verbose_name='Entregue'),
        ),
        migrations.AddField(
            model_name='despesa',
            name='descricao',
            field=models.CharField(blank=True, max_length=100, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='despesa',
            name='recorrente',
            field=models.BooleanField(default=False, verbose_name='Recorrente'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='avaliacao',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Avaliação'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='prazo_de_entraga',
            field=models.CharField(blank=True, max_length=20, verbose_name='Prazo Entrega Dias'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefone'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ativo',
            field=models.BooleanField(default=False, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='produto',
            name='marca',
            field=models.CharField(blank=True, max_length=100, verbose_name='Marca'),
        ),
        migrations.AddField(
            model_name='produto',
            name='preco_custo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Preco Custo'),
        ),
        migrations.AddField(
            model_name='produto',
            name='subcategoria',
            field=models.CharField(blank=True, max_length=100, verbose_name='Sub-Categoria'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='compra',
            field=models.ForeignKey(blank=True, db_column='id_compra', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='despesas', to='mercadinho.comprafornecedor', verbose_name='Compra vinculada'),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='id_estoque',
            field=models.AutoField(max_length=10, primary_key=True, serialize=False, verbose_name='ID do estoque'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='salario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Salario'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='cliente',
            field=models.ForeignKey(blank=True, db_column='id_cliente', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendas', to='mercadinho.cliente', verbose_name='Cliente'),
        ),
    ]
