# Generated by Django 6.0.4 on 2026-04-24 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercadinho', '0002_remove_cliente_qtd_comprada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='nome_fantasia',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Nome_Fantasia'),
        ),
    ]
