# Generated by Django 6.0.4 on 2026-04-29 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercadinho', '0003_fornecedor_nome_fantasia'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoque',
            name='dt_ultima_entrada',
            field=models.DateField(blank=True, null=True, verbose_name='Data da última entrada'),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='id_estoque',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID do estoque'),
        ),
    ]
