# Generated by Django 6.0.4 on 2026-04-30 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercadinho', '0004_estoque_dt_ultima_entrada_alter_estoque_id_estoque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='id_estoque',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='ID do estoque'),
        ),
    ]
