# Generated by Django 6.0.4 on 2026-05-01 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mercadinho', '0005_alter_estoque_id_estoque'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemvenda',
            name='preco_unitario',
        ),
    ]
