# Generated by Django 6.0.4 on 2026-05-02 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercadinho', '0005_alter_estoque_id_estoque'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprafornecedor',
            name='nome',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Nome da compra'),
        ),
    ]
