# Generated by Django 6.0.4 on 2026-05-02 14:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercadinho', '0006_remove_itemvenda_preco_unitario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemvenda',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=100, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Subtotal'),
        ),
    ]
