# Generated by Django 6.0.4 on 2026-05-02 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercadinho', '0007_venda_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='fornecedor',
            field=models.ForeignKey(blank=True, db_column='id_fornecedor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='mercadinho.fornecedor', verbose_name='Fornecedor'),
        ),
    ]
