# Generated by Django 6.0.4 on 2026-05-02 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mercadinho', '0007_alter_itemvenda_subtotal'),
        ('mercadinho', '0008_produto_fornecedor'),
    ]

    operations = [
    ]
