# Generated by Django 6.0.4 on 2026-05-08 03:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercadinho', '0009_remove_unique_constraints'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimentoFiado',
            fields=[
                ('id_movimento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('saldo_inicial', 'Saldo inicial'), ('venda_fiada', 'Venda fiada'), ('pagamento', 'Pagamento'), ('ajuste_edicao', 'Ajuste por edicao')], max_length=30, verbose_name='Tipo')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('saldo_anterior', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Saldo anterior')),
                ('saldo_atual', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Saldo atual')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.CASCADE, related_name='movimentos_fiado', to='mercadinho.cliente', verbose_name='Cliente')),
                ('venda', models.ForeignKey(blank=True, db_column='id_venda', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentos_fiado', to='mercadinho.venda', verbose_name='Venda vinculada')),
            ],
            options={
                'verbose_name': 'Movimento de fiado',
                'verbose_name_plural': 'Movimentos de fiado',
                'ordering': ['-criado_em', '-id_movimento'],
            },
        ),
    ]
